addSbtPlugin("com.github.sbt"          % "sbt-release"         % "1.5.0")
addSbtPlugin("com.github.sbt"          % "sbt-pgp"             % "2.3.2")
addSbtPlugin("org.xerial.sbt"          % "sbt-sonatype"        % "3.12.2")
addSbtPlugin("com.timushev.sbt"        % "sbt-updates"         % "0.7.0")
addSbtPlugin("com.github.sbt"          % "sbt-native-packager" % "1.12.0")
addSbtPlugin("ch.epfl.scala"           % "sbt-scalafix"        % "0.14.9")
addSbtPlugin("org.playframework.twirl" % "sbt-twirl"           % "2.0.9")
